// <auto-generated />
using System;
using IPLStore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPLStore.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IPLStoreDbContext))]
    partial class IPLStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPLStore.Domain.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("IPLStore.Domain.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("IPLStore.Domain.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MI",
                            Name = "Mumbai Indians"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CSK",
                            Name = "Chennai Super Kings"
                        },
                        new
                        {
                            Id = 3,
                            Code = "RCB",
                            Name = "Royal Challengers Bengaluru"
                        },
                        new
                        {
                            Id = 4,
                            Code = "KKR",
                            Name = "Kolkata Knight Riders"
                        });
                });

            modelBuilder.Entity("IPLStore.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("OrderedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OrderedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IPLStore.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("IPLStore.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("Name");

                    b.HasIndex("FranchiseId", "Type");

                    b.HasIndex("Type", "IsActive");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Official blue match jersey inspired by the Mumbai Indians home kit.",
                            FranchiseId = 1,
                            IsActive = true,
                            Name = "Mumbai Indians Match Jersey",
                            Price = 2499m,
                            RowVersion = new byte[0],
                            StockQty = 50,
                            Type = "Jersey"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Adjustable supporter cap with the Mumbai Indians crest embroidered on the front.",
                            FranchiseId = 1,
                            IsActive = true,
                            Name = "Mumbai Indians Supporter Cap",
                            Price = 799m,
                            RowVersion = new byte[0],
                            StockQty = 80,
                            Type = "Cap"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bright yellow fan jersey for Chennai Super Kings match days.",
                            FranchiseId = 2,
                            IsActive = true,
                            Name = "Chennai Super Kings Fan Jersey",
                            Price = 2299m,
                            RowVersion = new byte[0],
                            StockQty = 60,
                            Type = "Jersey"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ceramic coffee mug featuring the roaring Chennai Super Kings identity.",
                            FranchiseId = 2,
                            IsActive = true,
                            Name = "Chennai Super Kings Coffee Mug",
                            Price = 499m,
                            RowVersion = new byte[0],
                            StockQty = 120,
                            Type = "Mug"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Premium black hoodie celebrating Royal Challengers Bengaluru home support.",
                            FranchiseId = 3,
                            IsActive = true,
                            Name = "RCB Stadium Hoodie",
                            Price = 2999m,
                            RowVersion = new byte[0],
                            StockQty = 35,
                            Type = "Hoodie"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Soft cotton tee with Royal Challengers Bengaluru signature graphics.",
                            FranchiseId = 3,
                            IsActive = true,
                            Name = "RCB Signature T-Shirt",
                            Price = 999m,
                            RowVersion = new byte[0],
                            StockQty = 90,
                            Type = "TShirt"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Purple and gold hand flag for Kolkata Knight Riders match day support.",
                            FranchiseId = 4,
                            IsActive = true,
                            Name = "KKR Match Day Flag",
                            Price = 349m,
                            RowVersion = new byte[0],
                            StockQty = 150,
                            Type = "Flag"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lightweight training jersey inspired by Kolkata Knight Riders practice wear.",
                            FranchiseId = 4,
                            IsActive = true,
                            Name = "KKR Training Jersey",
                            Price = 1999m,
                            RowVersion = new byte[0],
                            StockQty = 45,
                            Type = "Jersey"
                        });
                });

            modelBuilder.Entity("IPLStore.Domain.CartItem", b =>
                {
                    b.HasOne("IPLStore.Domain.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPLStore.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IPLStore.Domain.OrderItem", b =>
                {
                    b.HasOne("IPLStore.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IPLStore.Domain.Product", b =>
                {
                    b.HasOne("IPLStore.Domain.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("IPLStore.Domain.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IPLStore.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
